name: protocol
description: json exchange protocol
version: 1.0.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  crypto: ^3.0.2
  hive: ^2.2.3
  hive_generator: ^2.0.0
  intl: '>=0.17.0 <0.19.0'
  json_annotation: ^4.8.0
  logging: ^1.1.1

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.21.0
  json_serializable: ^6.6.0
  build_runner: ^2.3.3

