name: server
description: A server app using the shelf package and Docker.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  args: ^2.3.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  protocol:
    path: ../protocol
  logging: ^1.1.1
  logging_appenders: ^1.0.0+2
  hive: ^2.2.3
  clock: ^1.1.1

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.3.3
